default:
	nvcc -o subtask1 assignment2_subtask1.cu
	nvcc -o subtask2 assignment2_subtask2.cu
	nvcc -o subtask3 assignment2_subtask3.cu
	nvcc -o subtask4 assignment2_subtask4.cu
clean:
	rm subtask1 subtask2 subtask3 subtask4